### ISSUE TITLE
Negative percentage if ship shields are set to 0 in ship template

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#54]
I'm wanting the player ship not to have shields (or set the value to zero so shields are effectively disabled)

When I use:
```
template:setShields(0, 0)
```

Displayed value of shields is: -2147483648% -2147483648% on Engineering screen. Should display 0% 0%

**Comment by daid** [comment]
It caused a division by zero, which resulted in a NaN, which in turn was converted to a MIN_INT value.

Should be fixed now with the patch I pushed.

**Comment by kwadroke** [comment]
Think you missed one part on _src/screens/crew6/engineeringScreen.cpp_. The rear shield is still displaying -2147483648% on the Engineering screen.

```
shields_display->setValue(string(my_spaceship->getFrontShieldPercentage()) + "% " + string(int(100 * my_spaceship->rear_shield / my_spaceship->rear_shield_max)) + "%");
```

Should be
```
shields_display->setValue(string(my_spaceship->getFrontShieldPercentage()) + "% " + string(my_spaceship->getRearShieldPercentage()) + "%");
```
